name: june_flutter
description: This package is Dart wrapper around the June HTTP API - which allows you to easily track data on June in your Dart projects and Flutter apps.
version: 0.0.3
repository: 'https://github.com/gaucidaniel/june_flutter'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
