name: june_flutter
description: June HTTP API wrapper
version: 0.0.1
repository: 'https://github.com/gaucidaniel/june_flutter'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
